In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics

from datasets import load_dataset

In [8]:
from datasets import load_dataset

from datasets import load_dataset

dataset = load_dataset(
    "csv",
    data_files={
        "aiml": r"dataset\aiml pre.csv",
        "business": r"dataset\business pre.csv",
        "cloud": r"dataset\cloud_infrastructure pre.csv",
        "design": r"dataset\design pre.csv",
        "developer": r"dataset\developer pre.csv",
        "marketing": r"dataset\marketing pre.csv",
        "product_management": r"dataset\product_management pre.csv"
    }
)

print(dataset)

Generating aiml split: 0 examples [00:00, ? examples/s]

Generating business split: 0 examples [00:00, ? examples/s]

Generating cloud split: 0 examples [00:00, ? examples/s]

Generating design split: 0 examples [00:00, ? examples/s]

Generating developer split: 0 examples [00:00, ? examples/s]

Generating marketing split: 0 examples [00:00, ? examples/s]

Generating product_management split: 0 examples [00:00, ? examples/s]

DatasetDict({
    aiml: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    business: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    cloud: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    design: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    developer: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    marketing: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
    product_management: Dataset({
        features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
        num_rows: 1500
    })
})

In [17]:
print(dataset["aiml"])
print(dataset["developer"])
print(dataset["design"])
print(dataset["marketing"])

Dataset({
    features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
    num_rows: 1500
})
Dataset({
    features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
    num_rows: 1500
})
Dataset({
    features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
    num_rows: 1500
})
Dataset({
    features: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text'],
    num_rows: 1500
})

In [18]:
import pandas as pd
import glob
import os

files = glob.glob("dataset/*.csv")

df = pd.concat(
    [pd.read_csv(file) for file in files],
    ignore_index=True
)

print("Total rows:", len(df))
print("Columns:", df.columns.tolist())
print(df["category"].value_counts())

Total rows: 10500
Columns: ['job_title', 'category', 'experience_level', 'experience_level_rank', 'employment_type', 'work_setting', 'industry', 'min_experience_years', 'max_experience_years', 'avg_experience_years', 'required_skills', 'skill_count', 'description', 'cleaned_description', 'nlp_corpus_text']
category
Data & AI                 1500
Business                  1500
Cloud & Infrastructure    1500
Design                    1500
Software Engineering      1500
Marketing                 1500
Product & Management      1500
Name: count, dtype: int64

In [23]:
df.head(5)

,job_title,category,experience_level,experience_level_rank,employment_type,work_setting,industry,min_experience_years,max_experience_years,avg_experience_years,required_skills,skill_count,description,cleaned_description,nlp_corpus_text
0,Junior Data Analyst,Data & AI,Junior,1,Contract,Remote,EdTech,1,3,2.0,Pandas; Power BI; Reporting; A/B Testing; Stat...,7,Contract · Remote. We are hiring a Junior Data...,Contract - Remote. We are hiring a Junior Data...,Junior Data Analyst | Data & AI | Junior | EdT...
1,Intern Data Engineer,Data & AI,Intern,0,Full-time,Hybrid,EdTech,0,1,0.5,Hadoop; AWS; Airflow; Kafka; Spark; Python,6,Full-time · Hybrid. We are hiring a Intern Dat...,Full-time - Hybrid. We are hiring a Intern Dat...,Intern Data Engineer | Data & AI | Intern | Ed...
2,Senior Data Analyst,Data & AI,Senior,3,Contract,Hybrid,EdTech,6,10,8.0,Python; Data Cleaning; Statistics; Excel; SQL,5,Contract · Hybrid. We are hiring a Senior Data...,Contract - Hybrid. We are hiring a Senior Data...,Senior Data Analyst | Data & AI | Senior | EdT...
3,Principal Data Engineer,Data & AI,Principal,5,Full-time,Remote,SaaS,12,20,16.0,ETL; AWS; Data Modeling; Python; Spark; Kafka,6,Full-time · Remote. We are hiring a Principal ...,Full-time - Remote. We are hiring a Principal ...,Principal Data Engineer | Data & AI | Principa...
4,Intern Data Analyst,Data & AI,Intern,0,Full-time,Hybrid,Enterprise,0,1,0.5,Python; A/B Testing; Power BI; SQL; Data Clean...,7,Full-time · Hybrid. We are hiring a Intern Dat...,Full-time - Hybrid. We are hiring a Intern Dat...,Intern Data Analyst | Data & AI | Intern | Ent...

In [22]:
df["category"]
df["experience_level_rank"]
df["required_skills"]

0        Pandas; Power BI; Reporting; A/B Testing; Stat...
1               Hadoop; AWS; Airflow; Kafka; Spark; Python
2            Python; Data Cleaning; Statistics; Excel; SQL
3            ETL; AWS; Data Modeling; Python; Spark; Kafka
4        Python; A/B Testing; Power BI; SQL; Data Clean...
                               ...
10495    Facilitation; Sprint Planning; Coaching; Agile...
10496    Agile; Budgeting; Reporting; Communication; Pr...
10497    Jira; Roadmapping; Agile; Backlog Management; ...
10498    Budgeting; Gantt Charts; Stakeholder Managemen...
10499    Communication; Agile; Prioritization; Stakehol...
Name: required_skills, Length: 10500, dtype: object

In [45]:
# x and y ------------

x = df[["category","experience_level_rank","required_skills","nlp_corpus_text"]]
x.columns
y = df["category"]

print(x.head(5))
print(y.head(5))

    category  experience_level_rank  \
0  Data & AI                      1
1  Data & AI                      0
2  Data & AI                      3
3  Data & AI                      5
4  Data & AI                      0

                                     required_skills  \
0  Pandas; Power BI; Reporting; A/B Testing; Stat...
1         Hadoop; AWS; Airflow; Kafka; Spark; Python
2      Python; Data Cleaning; Statistics; Excel; SQL
3      ETL; AWS; Data Modeling; Python; Spark; Kafka
4  Python; A/B Testing; Power BI; SQL; Data Clean...

                                     nlp_corpus_text
0  Junior Data Analyst | Data & AI | Junior | EdT...
1  Intern Data Engineer | Data & AI | Intern | Ed...
2  Senior Data Analyst | Data & AI | Senior | EdT...
3  Principal Data Engineer | Data & AI | Principa...
4  Intern Data Analyst | Data & AI | Intern | Ent...
0    Data & AI
1    Data & AI
2    Data & AI
3    Data & AI
4    Data & AI
Name: category, dtype: object

In [46]:
# check null / 0 values -

df["category"].isna().unique()

x.isna()

       category  experience_level_rank  required_skills  nlp_corpus_text
0         False                  False            False            False
1         False                  False            False            False
2         False                  False            False            False
3         False                  False            False            False
4         False                  False            False            False
...         ...                    ...              ...              ...
10495     False                  False            False            False
10496     False                  False            False            False
10497     False                  False            False            False
10498     False                  False            False            False
10499     False                  False            False            False

[10500 rows x 4 columns]